# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/julian/uni/visual/PS/Assignment_3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/julian/uni/visual/PS/Assignment_3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/julian/uni/visual/PS/Assignment_3/CMakeFiles /home/julian/uni/visual/PS/Assignment_3//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/julian/uni/visual/PS/Assignment_3/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named assignment_03

# Build rule for target.
assignment_03: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 assignment_03
.PHONY : assignment_03

# fast build rule for target.
assignment_03/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assignment_03.dir/build.make CMakeFiles/assignment_03.dir/build
.PHONY : assignment_03/fast

#=============================================================================
# Target rules for targets named assignment_01_copy_shader

# Build rule for target.
assignment_01_copy_shader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 assignment_01_copy_shader
.PHONY : assignment_01_copy_shader

# fast build rule for target.
assignment_01_copy_shader/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assignment_01_copy_shader.dir/build.make CMakeFiles/assignment_01_copy_shader.dir/build
.PHONY : assignment_01_copy_shader/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) $(MAKESILENT) -f external/glad/CMakeFiles/glad.dir/build.make external/glad/CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named stb_image

# Build rule for target.
stb_image: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stb_image
.PHONY : stb_image

# fast build rule for target.
stb_image/fast:
	$(MAKE) $(MAKESILENT) -f external/stb_image/CMakeFiles/stb_image.dir/build.make external/stb_image/CMakeFiles/stb_image.dir/build
.PHONY : stb_image/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f external/glfw/CMakeFiles/uninstall.dir/build.make external/glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f external/glfw/src/CMakeFiles/glfw.dir/build.make external/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f external/glfw/src/CMakeFiles/update_mappings.dir/build.make external/glfw/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

src/assignment_3.o: src/assignment_3.cpp.o
.PHONY : src/assignment_3.o

# target to build an object file
src/assignment_3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assignment_03.dir/build.make CMakeFiles/assignment_03.dir/src/assignment_3.cpp.o
.PHONY : src/assignment_3.cpp.o

src/assignment_3.i: src/assignment_3.cpp.i
.PHONY : src/assignment_3.i

# target to preprocess a source file
src/assignment_3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assignment_03.dir/build.make CMakeFiles/assignment_03.dir/src/assignment_3.cpp.i
.PHONY : src/assignment_3.cpp.i

src/assignment_3.s: src/assignment_3.cpp.s
.PHONY : src/assignment_3.s

# target to generate assembly for a file
src/assignment_3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assignment_03.dir/build.make CMakeFiles/assignment_03.dir/src/assignment_3.cpp.s
.PHONY : src/assignment_3.cpp.s

src/flag.o: src/flag.cpp.o
.PHONY : src/flag.o

# target to build an object file
src/flag.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assignment_03.dir/build.make CMakeFiles/assignment_03.dir/src/flag.cpp.o
.PHONY : src/flag.cpp.o

src/flag.i: src/flag.cpp.i
.PHONY : src/flag.i

# target to preprocess a source file
src/flag.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assignment_03.dir/build.make CMakeFiles/assignment_03.dir/src/flag.cpp.i
.PHONY : src/flag.cpp.i

src/flag.s: src/flag.cpp.s
.PHONY : src/flag.s

# target to generate assembly for a file
src/flag.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assignment_03.dir/build.make CMakeFiles/assignment_03.dir/src/flag.cpp.s
.PHONY : src/flag.cpp.s

src/math/matrix3d.o: src/math/matrix3d.cpp.o
.PHONY : src/math/matrix3d.o

# target to build an object file
src/math/matrix3d.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assignment_03.dir/build.make CMakeFiles/assignment_03.dir/src/math/matrix3d.cpp.o
.PHONY : src/math/matrix3d.cpp.o

src/math/matrix3d.i: src/math/matrix3d.cpp.i
.PHONY : src/math/matrix3d.i

# target to preprocess a source file
src/math/matrix3d.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assignment_03.dir/build.make CMakeFiles/assignment_03.dir/src/math/matrix3d.cpp.i
.PHONY : src/math/matrix3d.cpp.i

src/math/matrix3d.s: src/math/matrix3d.cpp.s
.PHONY : src/math/matrix3d.s

# target to generate assembly for a file
src/math/matrix3d.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assignment_03.dir/build.make CMakeFiles/assignment_03.dir/src/math/matrix3d.cpp.s
.PHONY : src/math/matrix3d.cpp.s

src/math/matrix4d.o: src/math/matrix4d.cpp.o
.PHONY : src/math/matrix4d.o

# target to build an object file
src/math/matrix4d.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assignment_03.dir/build.make CMakeFiles/assignment_03.dir/src/math/matrix4d.cpp.o
.PHONY : src/math/matrix4d.cpp.o

src/math/matrix4d.i: src/math/matrix4d.cpp.i
.PHONY : src/math/matrix4d.i

# target to preprocess a source file
src/math/matrix4d.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assignment_03.dir/build.make CMakeFiles/assignment_03.dir/src/math/matrix4d.cpp.i
.PHONY : src/math/matrix4d.cpp.i

src/math/matrix4d.s: src/math/matrix4d.cpp.s
.PHONY : src/math/matrix4d.s

# target to generate assembly for a file
src/math/matrix4d.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assignment_03.dir/build.make CMakeFiles/assignment_03.dir/src/math/matrix4d.cpp.s
.PHONY : src/math/matrix4d.cpp.s

src/math/vector2d.o: src/math/vector2d.cpp.o
.PHONY : src/math/vector2d.o

# target to build an object file
src/math/vector2d.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assignment_03.dir/build.make CMakeFiles/assignment_03.dir/src/math/vector2d.cpp.o
.PHONY : src/math/vector2d.cpp.o

src/math/vector2d.i: src/math/vector2d.cpp.i
.PHONY : src/math/vector2d.i

# target to preprocess a source file
src/math/vector2d.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assignment_03.dir/build.make CMakeFiles/assignment_03.dir/src/math/vector2d.cpp.i
.PHONY : src/math/vector2d.cpp.i

src/math/vector2d.s: src/math/vector2d.cpp.s
.PHONY : src/math/vector2d.s

# target to generate assembly for a file
src/math/vector2d.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assignment_03.dir/build.make CMakeFiles/assignment_03.dir/src/math/vector2d.cpp.s
.PHONY : src/math/vector2d.cpp.s

src/math/vector3d.o: src/math/vector3d.cpp.o
.PHONY : src/math/vector3d.o

# target to build an object file
src/math/vector3d.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assignment_03.dir/build.make CMakeFiles/assignment_03.dir/src/math/vector3d.cpp.o
.PHONY : src/math/vector3d.cpp.o

src/math/vector3d.i: src/math/vector3d.cpp.i
.PHONY : src/math/vector3d.i

# target to preprocess a source file
src/math/vector3d.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assignment_03.dir/build.make CMakeFiles/assignment_03.dir/src/math/vector3d.cpp.i
.PHONY : src/math/vector3d.cpp.i

src/math/vector3d.s: src/math/vector3d.cpp.s
.PHONY : src/math/vector3d.s

# target to generate assembly for a file
src/math/vector3d.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assignment_03.dir/build.make CMakeFiles/assignment_03.dir/src/math/vector3d.cpp.s
.PHONY : src/math/vector3d.cpp.s

src/math/vector4d.o: src/math/vector4d.cpp.o
.PHONY : src/math/vector4d.o

# target to build an object file
src/math/vector4d.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assignment_03.dir/build.make CMakeFiles/assignment_03.dir/src/math/vector4d.cpp.o
.PHONY : src/math/vector4d.cpp.o

src/math/vector4d.i: src/math/vector4d.cpp.i
.PHONY : src/math/vector4d.i

# target to preprocess a source file
src/math/vector4d.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assignment_03.dir/build.make CMakeFiles/assignment_03.dir/src/math/vector4d.cpp.i
.PHONY : src/math/vector4d.cpp.i

src/math/vector4d.s: src/math/vector4d.cpp.s
.PHONY : src/math/vector4d.s

# target to generate assembly for a file
src/math/vector4d.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assignment_03.dir/build.make CMakeFiles/assignment_03.dir/src/math/vector4d.cpp.s
.PHONY : src/math/vector4d.cpp.s

src/mygl/base.o: src/mygl/base.cpp.o
.PHONY : src/mygl/base.o

# target to build an object file
src/mygl/base.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assignment_03.dir/build.make CMakeFiles/assignment_03.dir/src/mygl/base.cpp.o
.PHONY : src/mygl/base.cpp.o

src/mygl/base.i: src/mygl/base.cpp.i
.PHONY : src/mygl/base.i

# target to preprocess a source file
src/mygl/base.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assignment_03.dir/build.make CMakeFiles/assignment_03.dir/src/mygl/base.cpp.i
.PHONY : src/mygl/base.cpp.i

src/mygl/base.s: src/mygl/base.cpp.s
.PHONY : src/mygl/base.s

# target to generate assembly for a file
src/mygl/base.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assignment_03.dir/build.make CMakeFiles/assignment_03.dir/src/mygl/base.cpp.s
.PHONY : src/mygl/base.cpp.s

src/mygl/camera.o: src/mygl/camera.cpp.o
.PHONY : src/mygl/camera.o

# target to build an object file
src/mygl/camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assignment_03.dir/build.make CMakeFiles/assignment_03.dir/src/mygl/camera.cpp.o
.PHONY : src/mygl/camera.cpp.o

src/mygl/camera.i: src/mygl/camera.cpp.i
.PHONY : src/mygl/camera.i

# target to preprocess a source file
src/mygl/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assignment_03.dir/build.make CMakeFiles/assignment_03.dir/src/mygl/camera.cpp.i
.PHONY : src/mygl/camera.cpp.i

src/mygl/camera.s: src/mygl/camera.cpp.s
.PHONY : src/mygl/camera.s

# target to generate assembly for a file
src/mygl/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assignment_03.dir/build.make CMakeFiles/assignment_03.dir/src/mygl/camera.cpp.s
.PHONY : src/mygl/camera.cpp.s

src/mygl/mesh.o: src/mygl/mesh.cpp.o
.PHONY : src/mygl/mesh.o

# target to build an object file
src/mygl/mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assignment_03.dir/build.make CMakeFiles/assignment_03.dir/src/mygl/mesh.cpp.o
.PHONY : src/mygl/mesh.cpp.o

src/mygl/mesh.i: src/mygl/mesh.cpp.i
.PHONY : src/mygl/mesh.i

# target to preprocess a source file
src/mygl/mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assignment_03.dir/build.make CMakeFiles/assignment_03.dir/src/mygl/mesh.cpp.i
.PHONY : src/mygl/mesh.cpp.i

src/mygl/mesh.s: src/mygl/mesh.cpp.s
.PHONY : src/mygl/mesh.s

# target to generate assembly for a file
src/mygl/mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assignment_03.dir/build.make CMakeFiles/assignment_03.dir/src/mygl/mesh.cpp.s
.PHONY : src/mygl/mesh.cpp.s

src/mygl/shader.o: src/mygl/shader.cpp.o
.PHONY : src/mygl/shader.o

# target to build an object file
src/mygl/shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assignment_03.dir/build.make CMakeFiles/assignment_03.dir/src/mygl/shader.cpp.o
.PHONY : src/mygl/shader.cpp.o

src/mygl/shader.i: src/mygl/shader.cpp.i
.PHONY : src/mygl/shader.i

# target to preprocess a source file
src/mygl/shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assignment_03.dir/build.make CMakeFiles/assignment_03.dir/src/mygl/shader.cpp.i
.PHONY : src/mygl/shader.cpp.i

src/mygl/shader.s: src/mygl/shader.cpp.s
.PHONY : src/mygl/shader.s

# target to generate assembly for a file
src/mygl/shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assignment_03.dir/build.make CMakeFiles/assignment_03.dir/src/mygl/shader.cpp.s
.PHONY : src/mygl/shader.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... assignment_01_copy_shader"
	@echo "... uninstall"
	@echo "... update_mappings"
	@echo "... assignment_03"
	@echo "... glad"
	@echo "... glfw"
	@echo "... stb_image"
	@echo "... src/assignment_3.o"
	@echo "... src/assignment_3.i"
	@echo "... src/assignment_3.s"
	@echo "... src/flag.o"
	@echo "... src/flag.i"
	@echo "... src/flag.s"
	@echo "... src/math/matrix3d.o"
	@echo "... src/math/matrix3d.i"
	@echo "... src/math/matrix3d.s"
	@echo "... src/math/matrix4d.o"
	@echo "... src/math/matrix4d.i"
	@echo "... src/math/matrix4d.s"
	@echo "... src/math/vector2d.o"
	@echo "... src/math/vector2d.i"
	@echo "... src/math/vector2d.s"
	@echo "... src/math/vector3d.o"
	@echo "... src/math/vector3d.i"
	@echo "... src/math/vector3d.s"
	@echo "... src/math/vector4d.o"
	@echo "... src/math/vector4d.i"
	@echo "... src/math/vector4d.s"
	@echo "... src/mygl/base.o"
	@echo "... src/mygl/base.i"
	@echo "... src/mygl/base.s"
	@echo "... src/mygl/camera.o"
	@echo "... src/mygl/camera.i"
	@echo "... src/mygl/camera.s"
	@echo "... src/mygl/mesh.o"
	@echo "... src/mygl/mesh.i"
	@echo "... src/mygl/mesh.s"
	@echo "... src/mygl/shader.o"
	@echo "... src/mygl/shader.i"
	@echo "... src/mygl/shader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

